// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

variable "environment" {
  description = "Environment in which the resource should be provisioned like dev, qa, prod etc."
  type        = string
  default     = "dev"
}

variable "resource_number" {
  description = "The resource count for the respective environment. Defaults to 000. Increments in value of 1"
  type        = string
  default     = "000"
}

variable "logical_product_family" {
  description = "Logical product family for which the resource is created. Example: org_name, department_name."
  type        = string
  default     = "dso"
}

variable "logical_product_service" {
  description = "Logical product service for which the resource is created. For example, backend, frontend, middleware etc."
  type        = string
  default     = "acr"
}

variable "environment_number" {
  description = "The environment count for the respective environment. Defaults to 000. Increments in value of 1"
  type        = string
  default     = "000"
}

variable "region" {
  description = "AWS Region in which the infra needs to be provisioned"
  type        = string
  default     = "eastus"
}

variable "resource_names_map" {
  description = "A map of key to resource_name that will be used by tf-launch-module_library-resource_name to generate resource names"
  type = map(object(
    {
      name       = string
      max_length = optional(number, 60)
    }
  ))
  default = {
    acr = {
      name       = "acr"
      max_length = 60
    }
    rg = {
      name       = "rg"
      max_length = 60
    }
    dnsrg = {
      name       = "dnsrg"
      max_length = 60
    }
    private_endpoint = {
      name       = "pe"
      max_length = 60
    }
    private_endpoint_service_connection = {
      name       = "pesc"
      max_length = 80
    }
    vnet = {
      name       = "vnet"
      max_length = 60
    }
    dnsvnet = {
      name       = "dnsvnet"
      max_length = 80
    }
    resource_group_vnet = {
      name       = "vnetrg"
      max_length = 80
    }
    private_dns_zone_link = {
      name       = "pdzl"
      max_length = 80
    }
  }
}

variable "use_azure_region_abbr" {
  description = "Whether to use Azure region abbreviation for azure region"
  type        = bool
  default     = true
}

variable "resource_group_name" {
  description = "Name of the resource group in which the ACR will be created. If not provided, this module will create one"
  type        = string
  default     = null
}

# variable "create_resource_group" {
#   description = "Whether to create a new resource group or use an existing one"
#   type        = bool
#   default     = true
# }

variable "container_registry_name" {
  type        = string
  description = "Container Registry name. If provided, then the name generated by the naming module won't be used"
  default     = null
}

variable "admin_enabled" {
  description = "Specifies whether the admin user is enabled. Defaults to true. When enabled, password tokens are generated to be used with docker login"
  type        = bool
  default     = false
}

variable "retention_policy" {
  description = "Set a retention policy for untagged manifests"
  type = object({
    days    = optional(number)
    enabled = optional(bool)
  })
  default = null
}

variable "identity_ids" {
  description = <<EOT
    Specifies a list of user managed identity ids to be assigned.
    This is required when `type` is set to `UserAssigned` or `SystemAssigned, UserAssigned`
  EOT
  type        = list(string)
  default     = null
}

variable "encryption" {
  description = "Encrypt registry using a customer-managed key"
  type = object({
    key_vault_key_id   = string
    identity_client_id = string
  })
  default = null
}

variable "public_network_access_enabled" {
  description = "Whether public network access is allowed for the container registry. Defaults to true."
  type        = bool
  default     = true
}

variable "network_rule_bypass_option" {
  description = <<EOT
    Whether to allow trusted Azure services to access a network restricted Container Registry? Possible values are
    None and AzureServices. Defaults to AzureServices
  EOT
  type        = string
  default     = "AzureServices"
}

variable "zone_redundancy_enabled" {
  description = <<EOT
    Whether zone redundancy is enabled for this Container Registry? Changing this forces a new resource to be created.
    Defaults to false
  EOT
  type        = bool
  default     = false
}

variable "georeplications" {
  description = "If specified, the ACR will be replicated to other regions specified in this block"
  type = map(object({
    location                  = string
    regional_endpoint_enabled = bool
    zone_redundancy_enabled   = bool
  }))

  default = {}
}

variable "network_rule_set" {
  description = <<EOT
    Network rules to explicitly allow IP ranges
    CIDR ranges should be provided
  EOT
  type        = list(string)
  default     = []
}

variable "acr_subnet_id" {
  description = "The ID of the subnet in which the private endpoint should be created."
  type        = string
  default     = null
}

variable "private_dns_zone_name" {
  description = "The name of the private DNS zone to which the private endpoint should be associated. Defaults to privatelink.azurecr.io, but needs to change for gov cloud."
  type        = string
  default     = "privatelink.azurecr.io"
}

variable "private_service_connection_name" {
  description = "The name of the private service connection. Defaults to pvt-connection-acr"
  type        = string
  default     = "pvt-connection-acr"
}

variable "private_dns_zone_group_name" {
  description = "The name of the private DNS zone group. Defaults to pvt-dns-group"
  type        = string
  default     = "pvt-dns-group"
}

variable "private_dns_zone_resource_group_name" {
  description = "The name of the resource group in which the private DNS zone is created. Defaults to null."
  type        = string
  default     = null
}


variable "acr_role_assignments" {
  description = "A map of role assignments to be created for the container registry"
  type = map(object({
    role_definition_name = string
    principal_id         = string
  }))
  default = {}
}

###########################################
# Variables related to private DNS zone
###########################################

variable "zone_name" {
  type        = string
  description = "Name of the private dns zone. For public cloud, the default value is `privatelink.azurecr.io` and for sovereign clouds, the default value is `privatelink.azurecr.us`"
  default     = "privatelink.azurecr.io"
  validation {
    condition     = contains(["privatelink.azurecr.io", "privatelink.azurecr.cr"], var.zone_name)
    error_message = "The zone_name must be either 'privatelink.azurecr.io' or 'privatelink.azurecr.us'."
  }
}

variable "create_private_dns_zone" {
  description = "Whether to create a private DNS zone. Defaults to true."
  type        = bool
  default     = true
}

variable "create_dns_vnet_link" {
  description = "Whether to create a VNet link for the private DNS zone. Defaults to true."
  type        = bool
  default     = true
}
########################################
# Variables related to virtual network
########################################

variable "use_for_each" {
  type        = bool
  description = "Use `for_each` instead of `count` to create multiple resource instances."
  default     = false
}

variable "address_space" {
  type        = list(string)
  description = "The address space that is used by the virtual network."
}

variable "bgp_community" {
  type        = string
  default     = null
  description = "(Optional) The BGP community attribute in format `<as-number>:<community-value>`."
}

variable "ddos_protection_plan" {
  type = object({
    enable = bool
    id     = string
  })
  default     = null
  description = "The set of DDoS protection plan configuration"
}

# If no values specified, this defaults to Azure DNS
variable "dns_servers" {
  type        = list(string)
  default     = []
  description = "The DNS servers to be used with vNet."
}

variable "nsg_ids" {
  type        = map(string)
  default     = {}
  description = "A map of subnet name to Network Security Group IDs"
}

variable "route_tables_ids" {
  type        = map(string)
  default     = {}
  description = "A map of subnet name to Route table ids"
}

variable "subnet_delegation" {
  type        = map(map(any))
  default     = {}
  description = "A map of subnet name to delegation block on the subnet"
}

variable "subnet_private_endpoint_network_policies_enabled" {
  type        = map(string)
  default     = {}
  description = "A map of subnet name to enable/disable private link service network policies on the subnet."
}

variable "subnet_names" {
  type        = list(string)
  description = "A list of public subnets inside the vNet."
}

variable "subnet_prefixes" {
  type        = list(string)
  description = "The address prefix to use for the subnet."
}

variable "subnet_service_endpoints" {
  type        = map(any)
  default     = {}
  description = "A map of subnet name to service endpoints to add to the subnet."
}

################################################
# Tags to be associated with all child modules
################################################
variable "tags" {
  description = "A map of tags to be associated with the resources"
  type        = map(string)
  default     = {}
}
